# Generated by Django 3.0.6 on 2020-05-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200529_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_post_id',
            new_name='comment_post',
        ),
    ]
